#################################################################
## Configuration
#################################################################

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 53
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret base_url

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:
  exclude:
    domains:
      - group
      - sensor.pihole

# Track the sun
sun:

sensor: !include sensors.yaml

# Text to speech
tts:
  platform: google

notify:
  - name: html5
    platform: html5
    gcm_api_key: !secret html5_server_key
    gcm_sender_id: !secret html5_sender_id
  
# mqtt:
  # broker: 127.0.0.1
  # port: 1883
  # client_id: home-assistant-1
  # username: pi
  # password: raspberry
  
### Z-WAVE CONFIG ###
zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/libopenzwave-0.3.2-py3.4-linux-armv7l.egg/config

### Nest Config ###
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  sensors:
    monitored_conditions:
      - 'humidity'
      - 'co_status'
      - 'smoke_status'
      - 'battery_health'
  binary_sensors:
    monitored_conditions:
      #None

### Wink Config ###
wink:
  email: !secret email
  password: !secret wink_password
  
ifttt:
  key: UXMNDj585Tsf5ocvyClf3

### Device Tracking ###
device_tracker:
  - platform: owntracks
  - platform: tplink
    host: !secret tplink_ip
    username: !secret tplink_username
    password: !secret tplink_password
    consider_home: 180
    track_new_devices: false
    
#################################################################
## Includes
#################################################################

mqtt: !include mqtt.yaml
zone: !include zones.yaml
#input_slider: !include input_sliders.yaml
automation: !include_dir_merge_list automation
group: !include groups.yaml
script: !include scripts.yaml
input_boolean: !include input_booleans.yaml